# Generated by Django 5.0.1 on 2024-02-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_categories_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='manufactured_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата производства'),
        ),
    ]
