# Generated by Django 5.0.1 on 2024-02-09 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_products_manufactured_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='manufactured_at',
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.categories'),
        ),
    ]
