# Generated by Django 5.0.1 on 2024-02-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, verbose_name='Слаг')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='catalog/blog', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('view_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
                'ordering': ('created_at', 'view_count'),
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='media/catalog', verbose_name='Изображение'),
        ),
    ]
