# Generated by Django 5.0.1 on 2024-02-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_blog_alter_products_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('price_per_one', 'created_at', 'view_count'), 'verbose_name': 'публикация', 'verbose_name_plural': 'публикации'},
        ),
        migrations.AddField(
            model_name='blog',
            name='price_per_one',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена за штуку'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='slug'),
        ),
    ]
