# Generated by Django 5.0.1 on 2024-03-07 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_blog_options_blog_price_per_one_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='номер версии')),
                ('name', models.CharField(max_length=150, verbose_name='Название версии')),
                ('working', models.BooleanField(default=False, verbose_name='Работает')),
                ('product', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='catalog.products', verbose_name='Продукт')),
            ],
        ),
    ]
