# Generated by Django 5.0.1 on 2024-03-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('product', 'number', 'name', 'working'), 'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
    ]
