# Generated by Django 5.0.1 on 2024-03-10 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_version_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='number',
            field=models.FloatField(default=1.0, verbose_name='Номер версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.products', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='version',
            name='working',
            field=models.BooleanField(default=True, verbose_name='Работает'),
        ),
    ]
