# Generated by Django 5.0.1 on 2024-03-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_version_name_alter_version_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='number',
            field=models.FloatField(verbose_name='Номер версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='working',
            field=models.BooleanField(verbose_name='Работает'),
        ),
    ]
