# Generated by Django 4.2 on 2024-03-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_version_number_alter_version_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=models.CharField(verbose_name='Телефон'),
        ),
    ]
